### ISSUE TITLE
Error op code 

### ISSUE THREAD

**Issue by BreNiiNx** [mehah/otclient#140]
This error occurs when monsters and their spells, it's probably because of extended effects

https://prnt.sc/1qi8jb2

**Comment by oarsc** [comment]
Looks like the server is sending something that the client doesn't understand.
Which server are you using? Did you modify it?

**Comment by BreNiiNx** [comment]
I'm using the client on a Dragon ball server, yes i made some changes

**Comment by mehah** [comment]
You are probably forgetting to enable the extended effects feature on the client or server.

command to enable "extended effect" on client:
```lua
g_game.enableFeature(GameMagicEffectU16)
```

**Comment by mehah** [comment]
I'm going to close, as your server contains modifications.

Note: You need to adapt the client to your needs.
