### ISSUE TITLE
Fps drop on opening modal windows

### ISSUE THREAD

**Issue by bulawow** [mehah/otclient#27]
### Steps to reproduce (include any configuration/script required to reproduce)
1.Opening outfit window (this one have the biggest fps drop) https://gyazo.com/96146a26d8eaef55955736ed0937b5af
2.On opening brose field https://gyazo.com/ff08c64210f8756da0a539ba1ba6b62b
3.spamming some smaller windows (fps drops on every icon there is) https://gyazo.com/898853a4cb1519a842afc6bafe228922

### Expected behaviour
should not drop fps

### Actual behaviour
dropping fps

### Environment
Otclient 1.0
Also checked if its happening in edubart client and i can confirm fps not dropping on edubart oclient while doing stuff i did in those gifs

**Comment by mehah** [comment]
it doesn't happen to me and nothing that affects the interface was touched, it wasn't even optimized and I don't intend, tile optimization is enough.

OBS: make sure you compiled in release mode and check that there is no error in the terminal.

Test:
https://i.imgur.com/dsIZcef.mp4

**Comment by bulawow** [comment]
U are 100% right sorry my bad i forgot that i had it in debug mode cause i was checking out the crash when trying to move while having looktype that had no animations sorry my bad, closing.
